export enum ProblemsType {
  _NP = "",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  BAD_INPUT_DATA = "BAD_INPUT_DATA",
  BAD_TOKEN = "BAD_TOKEN",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  FAILED_LOGOUT = "FAILED_LOGOUT",
  USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
  EMAIL_OCCUPIED = "EMAIL_OCCUPIED",
  EMAIL_IS_NOT_VALID = "EMAIL_IS_NOT_VALID",
  INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
  UNSUITABLE_PASSWORD = "UNSUITABLE_PASSWORD",
  BAD_INTERNET_CONNECTION = "BAD_INTERNET_CONNECTION",
}
